updates on binutils, gcc and autoreconf
gcc version updated to 4.2.4;
canonical binutils version is 2.17;
note on binutils-2.18 build system bug;
one more detail of autoreconf procedure

diff --git a/README b/README
--- a/README
+++ b/README
@@ -102,12 +102,11 @@ HOW TO INSTALL DEVELOPMENT TOOLS
 First, we shall need binutils and gcc for ARM. we go to http://www.gnu.org and
 get binutils and gcc. generally, we use the latest releases, though there is 
 nothing dependent on any supernew features in stribog. currently we use 
-binutils-2.18 with gcc-4.2.3. we used also binutils-2.17, binutils-2.16.1, 
-binutils-2.16, gcc-3.4.6, gcc-4.0.1, gcc-4.0.3, gcc-4.1.1, gcc-4.1.2,
-gcc-4.2.2.
+binutils-2.17 with gcc-4.2.4. we used also binutils-2.16.1, binutils-2.16,
+gcc-3.4.6, gcc-4.0.1, gcc-4.0.3, gcc-4.1.1, gcc-4.1.2, gcc-4.2.2, gcc-4.2.3.
 
 The oldest versions of tools known to successfully build
-the ARM programs are binutils-2.11.2 and gcc-3.3.6.
+the ARM programs are binutils-2.11.2 and gcc-3.3.4.
 we can't make our buggy programs work with earlier releases.
 
 gcc-3.3.6 will not build itself on binutils-2.10.1
@@ -126,16 +125,16 @@ Follow (with some changes) instructions from http://www.gnuarm.com
 $ export armprefix=$HOME/arm
                    (or where you want them to live. you must have write access
 		    thither when you will `make install')
-$ gpg --verify binutils-2.18.tar.bz2.sig && tar xjf binutils-2.18.tar.bz2
+$ gpg --verify binutils-2.17.tar.bz2.sig && tar xjf binutils-2.17.tar.bz2
 $ mkdir bui;cd bui
-$ ../binutils-2.18/configure --target=arm-unknown-elf --prefix=$armprefix --enable-interwork --enable-multilib
+$ ../binutils-2.17/configure --target=arm-unknown-elf --prefix=$armprefix
 $ make all install
 $ export PATH=$armprefix/bin:$PATH; rm -fr *;cd ..
  #(add this path in your shell profile after install, too)
  #note: some gcc will not build itself when configured with a prefix
  #other than that of binutils
-$ gpg --verify gcc-4.2.3.tar.bz2.sig && tar xjf gcc-4.2.3.tar.bz2;cd bui
-$ ../gcc-4.2.3/configure --target=arm-unknown-elf --prefix=$armprefix --enable-interwork --enable-multilib --enable-languages=c --disable-libssp
+$ gpg --verify gcc-4.2.4.tar.bz2.sig && tar xjf gcc-4.2.4.tar.bz2;cd bui
+$ ../gcc-4.2.4/configure --target=arm-unknown-elf --prefix=$armprefix --enable-languages=c --disable-libssp
 $ make all install
 
 That's all. we don't need newlib, and stribog main board has no contacts 
@@ -155,11 +154,69 @@ This sequence was tested on
 (2) OpenBSD 3.9 (i386, native gcc-3.3.5).
 as we mentioned, it is recommended to use gmake instead of make.
 (3) On RedHat 7.3 (native gcc-2.96).
-binutils-2.18 will not build themselves
-without manual intervention. binutils-2.17 with gcc-4.2.3 work just fine;
-generally, binutils-2.18 release is not very stable.
-BTW on RedHat 7.3 you shall need to update gnupg. it comes with 1.0.6 version
+you shall need to update gnupg. it comes with 1.0.6 version
 and it can't check new signatures; gnupg-1.4.9 is quite buildable there.
+
+Build system of binutils-2.18 is broken; the build process stops in bfd/doc.
+quick and dirty fix is to patch `missing':
+
+--- binutils-2.18/missing	2005-07-14 05:24:56.000000000 +0400
++++ missing	2008-05-24 10:53:30.000000000 +0400
+@@ -27,5 +27,5 @@
+ # configuration script generated by Autoconf, you may include it under
+ # the same distribution terms that you use for the rest of that program.
+-
++# May 2008, ineiev: changed to build binutils-2.18
+ if test $# -eq 0; then
+   echo 1>&2 "Try \`$0 --help' for more information"
+@@ -46,19 +46,4 @@
+ 
+ case "$1" in
+---run)
+-  # Try to run requested program, and just exit if it succeeds.
+-  run=
+-  shift
+-  "$@" && exit 0
+-  # Exit code 63 means version mismatch.  This often happens
+-  # when the user try to use an ancient version of a tool on
+-  # a file that requires a minimum version.  In this case we
+-  # we should proceed has if the program had been absent, or
+-  # if --run hadn't been passed.
+-  if test $? = 63; then
+-    run=:
+-    msg="probably too old"
+-  fi
+-  ;;
+ 
+   -h|--h|--he|--hel|--help)
+@@ -101,7 +86,23 @@
+     exit 1
+     ;;
++*)
++  # Try to run requested program, and just exit if it succeeds.
++  run=
++  if test $1 = "--run"; then
++    shift
++  fi
++  "$@" && exit 0
++  # Exit code 63 means version mismatch.  This often happens
++  # when the user try to use an ancient version of a tool on
++  # a file that requires a minimum version.  In this case we
++  # we should proceed has if the program had been absent, or
++  # if --run hadn't been passed.
++  if test $? = 63; then
++    run=:
++    msg="probably too old"
++  fi
++  ;;
+ 
+ esac
+-
+ # Now exit if we have it, but it failed.  Also exit now if we
+ # don't have it and --version was passed (most likely to detect
+
+The problem was obviously not in `missing', but in automake-1.9.6, 
+which was used to regenerate the build system.
 
 GCC-4.3.0 has a new strong dependency, MPFR. we can't recommend it
 because MPFR distribution comes with no signature. current version of MPFR,
@@ -242,6 +299,10 @@ The configuring scripts are updated with 'autoreconf -v';
 you may 'rm -rf $(find . -name autom4te.cache)' after that.
 
 As of May 2008, the versions used are autoconf-2.62 and automake-1.10.1.
+
+For some subdirectories regeneration some portions of build system
+(particularly, Makefile.ams) needs building the project
+(the corresponding Makefiles contain a rule to refresh those files).
 
 HOW TO USE GIT
 
