./regen_configure

diff --git a/sw/host/configure b/sw/host/configure
--- a/sw/host/configure
+++ b/sw/host/configure
@@ -702,12 +702,12 @@ RANLIB
 CPP
 GREP
 EGREP
-argp_lib
-build_own_argp_TRUE
-build_own_argp_FALSE
 LIBOBJS
+argp_lib
 the_host_is_windows_TRUE
 the_host_is_windows_FALSE
+build_own_argp_TRUE
+build_own_argp_FALSE
 stribog_lib
 LTLIBOBJS'
 ac_subst_files=''
@@ -3502,7 +3502,7 @@ else
 fi
 
 
-if test "z$GCC" = "zyes"; then
+if test "z$GCC" = zyes; then
  CFLAGS="${CFLAGS} -Wall"
 fi
 
@@ -4369,235 +4369,6 @@ fi
 done
 
 
-#argp library configuration
-if test "z$build_own_argp" = "z";then
- { echo "$as_me:$LINENO: checking if stribog argp implementation is asked for" >&5
-echo $ECHO_N "checking if stribog argp implementation is asked for... $ECHO_C" >&6; }
- # Check whether --enable-own-argp was given.
-if test "${enable_own_argp+set}" = set; then
-  enableval=$enable_own_argp;
-fi
-
- if test "z$enable_own_argp" != "zyes";then
-  enable_own_argp=no
- fi
- { echo "$as_me:$LINENO: result: $enable_own_argp" >&5
-echo "${ECHO_T}$enable_own_argp" >&6; }
- build_own_argp=$enable_own_argp
- if test "z$enable_own_argp" = "zno";then
-  if test "${ac_cv_header_argp_h+set}" = set; then
-  { echo "$as_me:$LINENO: checking for argp.h" >&5
-echo $ECHO_N "checking for argp.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_argp_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_argp_h" >&5
-echo "${ECHO_T}$ac_cv_header_argp_h" >&6; }
-else
-  # Is the header compilable?
-{ echo "$as_me:$LINENO: checking argp.h usability" >&5
-echo $ECHO_N "checking argp.h usability... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <argp.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_header_compiler=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6; }
-
-# Is the header present?
-{ echo "$as_me:$LINENO: checking argp.h presence" >&5
-echo $ECHO_N "checking argp.h presence... $ECHO_C" >&6; }
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <argp.h>
-_ACEOF
-if { (ac_try="$ac_cpp conftest.$ac_ext"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null && {
-	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       }; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-  ac_header_preproc=no
-fi
-
-rm -f conftest.err conftest.$ac_ext
-{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6; }
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
-  yes:no: )
-    { echo "$as_me:$LINENO: WARNING: argp.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: argp.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: argp.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: argp.h: proceeding with the compiler's result" >&2;}
-    ac_header_preproc=yes
-    ;;
-  no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: argp.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: argp.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: argp.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: argp.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: argp.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: argp.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: argp.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: argp.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: argp.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: argp.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: argp.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: argp.h: in the future, the compiler will take precedence" >&2;}
-    ( cat <<\_ASBOX
-## ------------------------------------- ##
-## Report this to stribog-bug@nongnu.org ##
-## ------------------------------------- ##
-_ASBOX
-     ) | sed "s/^/$as_me: WARNING:     /" >&2
-    ;;
-esac
-{ echo "$as_me:$LINENO: checking for argp.h" >&5
-echo $ECHO_N "checking for argp.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_argp_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_argp_h=$ac_header_preproc
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_argp_h" >&5
-echo "${ECHO_T}$ac_cv_header_argp_h" >&6; }
-
-fi
-if test $ac_cv_header_argp_h = yes; then
-  :
-else
-  { echo "$as_me:$LINENO: result: no usable argp.h found; stribog version will be used" >&5
-echo "${ECHO_T}no usable argp.h found; stribog version will be used" >&6; }
-    build_own_argp=yes
-
-fi
-
-
- fi
-else
- { echo "$as_me:$LINENO: result: argp implementation seems to have been already selected" >&5
-echo "${ECHO_T}argp implementation seems to have been already selected" >&6; }
-fi
-if test "z$build_own_argp" = "zyes";then
- { echo "$as_me:$LINENO: checking for error_t" >&5
-echo $ECHO_N "checking for error_t... $ECHO_C" >&6; }
-if test "${ac_cv_type_error_t+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-typedef error_t ac__type_new_;
-int
-main ()
-{
-if ((ac__type_new_ *) 0)
-  return 0;
-if (sizeof (ac__type_new_))
-  return 0;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  ac_cv_type_error_t=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_type_error_t=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_type_error_t" >&5
-echo "${ECHO_T}$ac_cv_type_error_t" >&6; }
-if test $ac_cv_type_error_t = yes; then
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_ERROR_T 1
-_ACEOF
-
-
-fi
-
- ac_config_files="$ac_config_files argp.h:lib/argp/argp.h"
-
- argp_lib="\$(top_builddir)/lib/argp/libargp.a"
-
-
 for ac_header in sysexits.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
@@ -4742,17 +4513,230 @@ fi
 
 done
 
+
+#argp library configuration
+{ echo "$as_me:$LINENO: checking if stribog argp implementation is asked for" >&5
+echo $ECHO_N "checking if stribog argp implementation is asked for... $ECHO_C" >&6; }
+# Check whether --enable-own-argp was given.
+if test "${enable_own_argp+set}" = set; then
+  enableval=$enable_own_argp;
 fi
- if test "z$build_own_argp" = "zyes"; then
-  build_own_argp_TRUE=
-  build_own_argp_FALSE='#'
+
+{ echo "$as_me:$LINENO: result: $enable_own_argp" >&5
+echo "${ECHO_T}$enable_own_argp" >&6; }
+if test "${ac_cv_header_argp_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for argp.h" >&5
+echo $ECHO_N "checking for argp.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_argp_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_argp_h" >&5
+echo "${ECHO_T}$ac_cv_header_argp_h" >&6; }
 else
-  build_own_argp_TRUE='#'
-  build_own_argp_FALSE=
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking argp.h usability" >&5
+echo $ECHO_N "checking argp.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <argp.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking argp.h presence" >&5
+echo $ECHO_N "checking argp.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <argp.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: argp.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: argp.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: argp.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: argp.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: argp.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: argp.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: argp.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: argp.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: argp.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: argp.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------------- ##
+## Report this to stribog-bug@nongnu.org ##
+## ------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for argp.h" >&5
+echo $ECHO_N "checking for argp.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_argp_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_argp_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_argp_h" >&5
+echo "${ECHO_T}$ac_cv_header_argp_h" >&6; }
+
+fi
+if test $ac_cv_header_argp_h = yes; then
+  :
+else
+  { echo "$as_me:$LINENO: result: no usable argp.h found; stribog version should be used" >&5
+echo "${ECHO_T}no usable argp.h found; stribog version should be used" >&6; }
+ build_own_argp=yes
+
 fi
 
 
+if test "z$enable_own_argp" = zno; then
+ if "z$build_own_argp" = zyes; then
+  { echo "$as_me:$LINENO: result: own argp disabled and no usable system argp available" >&5
+echo "${ECHO_T}own argp disabled and no usable system argp available" >&6; }
+  exit 1;
+ fi
+fi
+if test "z$enable_own_argp" = zyes; then
+ build_own_argp=yes
+fi
 # Checks for typedefs, structures, and compiler characteristics.
+{ echo "$as_me:$LINENO: checking for error_t" >&5
+echo $ECHO_N "checking for error_t... $ECHO_C" >&6; }
+if test "${ac_cv_type_error_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+typedef error_t ac__type_new_;
+int
+main ()
+{
+if ((ac__type_new_ *) 0)
+  return 0;
+if (sizeof (ac__type_new_))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_type_error_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_type_error_t=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_type_error_t" >&5
+echo "${ECHO_T}$ac_cv_type_error_t" >&6; }
+if test $ac_cv_type_error_t = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_ERROR_T 1
+_ACEOF
+
+
+fi
+
 { echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
 echo $ECHO_N "checking for an ANSI C-conforming const... $ECHO_C" >&6; }
 if test "${ac_cv_c_const+set}" = set; then
@@ -5733,12 +5717,26 @@ case $host in
 		the_host_is_windows=yes
 		;;
 esac
+if test "z$build_own_argp" = "zyes";then
+ ac_config_files="$ac_config_files argp.h:lib/argp/argp.h"
+
+ argp_lib="\$(top_builddir)/lib/argp/libargp.a"
+
+fi
  if test "z$the_host_is_windows" = "zyes"; then
   the_host_is_windows_TRUE=
   the_host_is_windows_FALSE='#'
 else
   the_host_is_windows_TRUE='#'
   the_host_is_windows_FALSE=
+fi
+
+ if test "z$build_own_argp" = "zyes"; then
+  build_own_argp_TRUE=
+  build_own_argp_FALSE='#'
+else
+  build_own_argp_TRUE='#'
+  build_own_argp_FALSE=
 fi
 
 
@@ -5863,17 +5861,17 @@ echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${build_own_argp_TRUE}" && test -z "${build_own_argp_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"build_own_argp\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"build_own_argp\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${the_host_is_windows_TRUE}" && test -z "${the_host_is_windows_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"the_host_is_windows\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"the_host_is_windows\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${build_own_argp_TRUE}" && test -z "${build_own_argp_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"build_own_argp\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"build_own_argp\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -6506,12 +6504,12 @@ RANLIB!$RANLIB$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
-argp_lib!$argp_lib$ac_delim
-build_own_argp_TRUE!$build_own_argp_TRUE$ac_delim
-build_own_argp_FALSE!$build_own_argp_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
+argp_lib!$argp_lib$ac_delim
 the_host_is_windows_TRUE!$the_host_is_windows_TRUE$ac_delim
 the_host_is_windows_FALSE!$the_host_is_windows_FALSE$ac_delim
+build_own_argp_TRUE!$build_own_argp_TRUE$ac_delim
+build_own_argp_FALSE!$build_own_argp_FALSE$ac_delim
 stribog_lib!$stribog_lib$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
