./regen_configure

diff --git a/sw/host/configure b/sw/host/configure
--- a/sw/host/configure
+++ b/sw/host/configure
@@ -5717,8 +5717,8 @@ case $host in
 		the_host_is_windows=yes
 		;;
 esac
-if test "z$build_own_argp" = "zyes";then
- ac_config_files="$ac_config_files argp.h:lib/argp/argp.h"
+if test "z$build_own_argp" = zyes;then
+ ac_config_links="$ac_config_links argp.h:lib/argp/argp.h"
 
  argp_lib="\$(top_builddir)/lib/argp/libargp.a"
 
@@ -5744,9 +5744,7 @@ stribog_lib="\$(top_builddir)/lib/libstribog.a"
 
 #common headers are copied to top build directory
 #to be available the same as config.h
-ac_config_files="$ac_config_files stribog_error.h:lib/stribog_error.h"
-
-ac_config_files="$ac_config_files stribog_strings.h:lib/stribog_strings.h"
+ac_config_links="$ac_config_links stribog_error.h:lib/stribog_error.h stribog_strings.h:lib/stribog_strings.h"
 
 #Makefiles are generated
 ac_config_files="$ac_config_files Makefile conloq/Makefile elk/Makefile intlpc/Makefile lib/Makefile lib/argp/Makefile postproc/Makefile utils/Makefile"
@@ -6193,6 +6191,7 @@ cat >>$CONFIG_STATUS <<_ACEOF
 # Files that config.status was made for.
 config_files="$ac_config_files"
 config_headers="$ac_config_headers"
+config_links="$ac_config_links"
 config_commands="$ac_config_commands"
 
 _ACEOF
@@ -6219,6 +6218,9 @@ $config_files
 
 Configuration headers:
 $config_headers
+
+Configuration links:
+$config_links
 
 Configuration commands:
 $config_commands
@@ -6344,9 +6346,9 @@ do
   case $ac_config_target in
     "config.h") CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
     "depfiles") CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
-    "argp.h") CONFIG_FILES="$CONFIG_FILES argp.h:lib/argp/argp.h" ;;
-    "stribog_error.h") CONFIG_FILES="$CONFIG_FILES stribog_error.h:lib/stribog_error.h" ;;
-    "stribog_strings.h") CONFIG_FILES="$CONFIG_FILES stribog_strings.h:lib/stribog_strings.h" ;;
+    "argp.h") CONFIG_LINKS="$CONFIG_LINKS argp.h:lib/argp/argp.h" ;;
+    "stribog_error.h") CONFIG_LINKS="$CONFIG_LINKS stribog_error.h:lib/stribog_error.h" ;;
+    "stribog_strings.h") CONFIG_LINKS="$CONFIG_LINKS stribog_strings.h:lib/stribog_strings.h" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
     "conloq/Makefile") CONFIG_FILES="$CONFIG_FILES conloq/Makefile" ;;
     "elk/Makefile") CONFIG_FILES="$CONFIG_FILES elk/Makefile" ;;
@@ -6370,6 +6372,7 @@ done
 if $ac_need_defaults; then
   test "${CONFIG_FILES+set}" = set || CONFIG_FILES=$config_files
   test "${CONFIG_HEADERS+set}" = set || CONFIG_HEADERS=$config_headers
+  test "${CONFIG_LINKS+set}" = set || CONFIG_LINKS=$config_links
   test "${CONFIG_COMMANDS+set}" = set || CONFIG_COMMANDS=$config_commands
 fi
 
@@ -6571,7 +6574,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF
 fi # test -n "$CONFIG_FILES"
 
 
-for ac_tag in  :F $CONFIG_FILES  :H $CONFIG_HEADERS    :C $CONFIG_COMMANDS
+for ac_tag in  :F $CONFIG_FILES  :H $CONFIG_HEADERS  :L $CONFIG_LINKS  :C $CONFIG_COMMANDS
 do
   case $ac_tag in
   :[FHLC]) ac_mode=$ac_tag; continue;;
@@ -6948,7 +6951,33 @@ echo X$ac_file |
 	  }
 	  s/.*/./; q'`/stamp-h$_am_stamp_count
  ;;
+  :L)
+  #
+  # CONFIG_LINK
+  #
 
+  { echo "$as_me:$LINENO: linking $srcdir/$ac_source to $ac_file" >&5
+echo "$as_me: linking $srcdir/$ac_source to $ac_file" >&6;}
+
+  if test ! -r "$srcdir/$ac_source"; then
+    { { echo "$as_me:$LINENO: error: $srcdir/$ac_source: file not found" >&5
+echo "$as_me: error: $srcdir/$ac_source: file not found" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  rm -f "$ac_file"
+
+  # Try a relative symlink, then a hard link, then a copy.
+  case $srcdir in
+  [\\/$]* | ?:[\\/]* ) ac_rel_source=$srcdir/$ac_source ;;
+      *) ac_rel_source=$ac_top_build_prefix$srcdir/$ac_source ;;
+  esac
+  ln -s "$ac_rel_source" "$ac_file" 2>/dev/null ||
+    ln "$srcdir/$ac_source" "$ac_file" 2>/dev/null ||
+    cp -p "$srcdir/$ac_source" "$ac_file" ||
+    { { echo "$as_me:$LINENO: error: cannot link or copy $srcdir/$ac_source to $ac_file" >&5
+echo "$as_me: error: cannot link or copy $srcdir/$ac_source to $ac_file" >&2;}
+   { (exit 1); exit 1; }; }
+ ;;
   :C)  { echo "$as_me:$LINENO: executing $ac_file commands" >&5
 echo "$as_me: executing $ac_file commands" >&6;}
  ;;
@@ -7112,7 +7141,7 @@ if test "$no_create" != yes; then
   $ac_cs_success || { (exit 1); exit 1; }
 fi
 
-if test "z$build_own_argp" = "zyes"; then
+if test "z$build_own_argp" = zyes; then
  argp_type=built-in
 else
  argp_type=GNU
@@ -7129,7 +7158,7 @@ echo "LDFLAGS:              ${LDFLAGS}">>summary
 echo "LIBS:                 ${LIBS}">>summary
 echo >>summary
 
-if test "z$recursive_stribog_build" != "zyes";then
+if test "z$recursive_stribog_build" != zyes;then
  { echo "$as_me:$LINENO: result: $(cat summary)" >&5
 echo "${ECHO_T}$(cat summary)" >&6; }
 fi
