autoreconf

diff --git a/sw/host/configure b/sw/host/configure
--- a/sw/host/configure
+++ b/sw/host/configure
@@ -1296,6 +1296,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --enable-own-argp       Use stribog implementation of argp library [no]
 
 Some influential environment variables:
   CC          C compiler command
@@ -4269,6 +4270,228 @@ fi
 done
 
 
+#argp library configuration
+{ echo "$as_me:$LINENO: checking if stribog argp implementation is asked for" >&5
+echo $ECHO_N "checking if stribog argp implementation is asked for... $ECHO_C" >&6; }
+# Check whether --enable-own-argp was given.
+if test "${enable_own_argp+set}" = set; then
+  enableval=$enable_own_argp;
+fi
+
+if test "z$enable_own_argp" != "zyes";then
+ enable_own_argp=no
+fi
+{ echo "$as_me:$LINENO: result: $enable_own_argp" >&5
+echo "${ECHO_T}$enable_own_argp" >&6; }
+build_own_argp=$enable_own_argp
+if test "z$enable_own_argp" = "zno";then
+ if test "${ac_cv_header_argp_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for argp.h" >&5
+echo $ECHO_N "checking for argp.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_argp_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_argp_h" >&5
+echo "${ECHO_T}$ac_cv_header_argp_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking argp.h usability" >&5
+echo $ECHO_N "checking argp.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <argp.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking argp.h presence" >&5
+echo $ECHO_N "checking argp.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <argp.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: argp.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: argp.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: argp.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: argp.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: argp.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: argp.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: argp.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: argp.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: argp.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: argp.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: argp.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ------------------------------------- ##
+## Report this to stribog-bug@nongnu.org ##
+## ------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for argp.h" >&5
+echo $ECHO_N "checking for argp.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_argp_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_argp_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_argp_h" >&5
+echo "${ECHO_T}$ac_cv_header_argp_h" >&6; }
+
+fi
+if test $ac_cv_header_argp_h = yes; then
+  :
+else
+  { echo "$as_me:$LINENO: result: no usable argp.h found; stribog version will be used" >&5
+echo "${ECHO_T}no usable argp.h found; stribog version will be used" >&6; }
+   build_own_argp=yes
+
+fi
+
+
+fi
+if test "z$build_own_argp" = "zyes";then
+ CPPFLAGS="$CPPFLAGS -I$srcdir/lib/argp"
+ { echo "$as_me:$LINENO: checking for error_t" >&5
+echo $ECHO_N "checking for error_t... $ECHO_C" >&6; }
+if test "${ac_cv_type_error_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+typedef error_t ac__type_new_;
+int
+main ()
+{
+if ((ac__type_new_ *) 0)
+  return 0;
+if (sizeof (ac__type_new_))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_type_error_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_type_error_t=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_type_error_t" >&5
+echo "${ECHO_T}$ac_cv_type_error_t" >&6; }
+if test $ac_cv_type_error_t = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_ERROR_T 1
+_ACEOF
+
+
+fi
+
+fi
+
 # Checks for typedefs, structures, and compiler characteristics.
 { echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
 echo $ECHO_N "checking for an ANSI C-conforming const... $ECHO_C" >&6; }
@@ -5244,12 +5467,13 @@ fi
 done
 
 
+#Checks for system services
 case $host in
         *-*-mingw32* | *-*-cygwin* | *-*-windows*)
 		the_host_is_windows=true
 		;;
 esac
- if test x$the_host_is_windows = xtrue; then
+ if test "x$the_host_is_windows" = "xtrue"; then
   the_host_is_windows_TRUE=
   the_host_is_windows_FALSE='#'
 else
@@ -6611,6 +6835,7 @@ Configuration summary for ${PACKAGE} ${VERSION}:
 
 prefix:               ${prefix}
 host:                 ${host}
+CPPFLAGS:             ${CPPFLAGS}
 CFLAGS:               ${CFLAGS}
 LIBS:                 ${LIBS}
 " >&5
@@ -6620,6 +6845,7 @@ Configuration summary for ${PACKAGE} ${VERSION}:
 
 prefix:               ${prefix}
 host:                 ${host}
+CPPFLAGS:             ${CPPFLAGS}
 CFLAGS:               ${CFLAGS}
 LIBS:                 ${LIBS}
 " >&6; }
